"""Finite synthetic ROS smoke fixture for the isolated BRNE shadow node."""

import json
import math
import time

import rclpy
from geometry_msgs.msg import PoseStamped, Twist
from nav_msgs.msg import Odometry, Path
from rclpy.node import Node

from resilient_nav_interfaces.msg import Pedestrian, PedestrianArray

from .brne_shadow_node import BrneShadowNode


class BrneShadowSmokeFixture(Node):
    """Publish fixed local inputs and assert bounded shadow-only outputs."""

    def __init__(self, shadow_node):
        """Create synthetic publishers and bounded observers without Gazebo or Nav2."""
        super().__init__('brne_shadow_smoke_fixture')
        self.shadow_node = shadow_node
        self.odom_publisher = self.create_publisher(Odometry, '/brne/odom', 10)
        self.goal_publisher = self.create_publisher(PoseStamped, '/brne/goal_pose', 10)
        self.pedestrian_publisher = self.create_publisher(
            PedestrianArray,
            '/brne/pedestrians',
            10,
        )
        self.create_subscription(Twist, '/brne/cmd_vel_raw', self._command_callback, 10)
        self.create_subscription(Path, '/brne/optimal_path', self._path_callback, 10)
        self.command = None
        self.path = None
        self.done = False
        self.failure = None
        self.inputs_enabled = True
        self.inputs_stopped_at = None
        self.zero_after_stop_at = None
        self.post_input_raw_stop_observed = False
        self.post_input_stop_latency_sec = None
        self.path_count = 0
        self.path_count_after_stop = None
        self.input_start = time.monotonic() + 0.8
        self.saw_zero_before_inputs = False
        self.deadline = time.monotonic() + 16.0
        self.create_timer(0.05, self._tick)

    def _tick(self):
        """Keep all inputs fresh until a real shadow plan has been observed."""
        if self.done:
            return
        if time.monotonic() >= self.deadline:
            self.failure = 'timeout waiting for finite BRNE shadow command and Path'
            self.done = True
            return
        if time.monotonic() < self.input_start:
            return
        if not self.inputs_enabled:
            self._complete_after_inputs_stop()
            return
        now = self.get_clock().now().to_msg()
        odom = Odometry()
        odom.header.frame_id = 'odom'
        odom.header.stamp = now
        odom.pose.pose.orientation.w = 1.0
        self.odom_publisher.publish(odom)

        goal = PoseStamped()
        goal.header.frame_id = 'odom'
        goal.header.stamp = now
        goal.pose.position.x = 2.0
        goal.pose.orientation.w = 1.0
        self.goal_publisher.publish(goal)

        pedestrians = PedestrianArray()
        pedestrians.header.frame_id = 'odom'
        pedestrians.header.stamp = now
        pedestrian = Pedestrian()
        pedestrian.header = pedestrians.header
        pedestrian.id = 1
        pedestrian.pose.position.x = 1.20
        pedestrian.pose.position.y = 0.50
        pedestrian.pose.orientation.w = 1.0
        pedestrian.velocity.linear.y = -0.10
        pedestrians.pedestrians.append(pedestrian)
        self.pedestrian_publisher.publish(pedestrians)
        self._complete_if_valid()

    def _command_callback(self, message):
        """Retain the latest raw command generated by the real shadow node."""
        now = time.monotonic()
        if (
            now < self.input_start
            and message.linear.x == 0.0
            and message.angular.z == 0.0
        ):
            self.saw_zero_before_inputs = True
        if (
            self.inputs_stopped_at is not None
            and message.linear.x == 0.0
            and message.angular.z == 0.0
            and not self.post_input_raw_stop_observed
        ):
            self.post_input_raw_stop_observed = True
            self.zero_after_stop_at = now
            self.post_input_stop_latency_sec = now - self.inputs_stopped_at
            self.path_count_after_stop = self.path_count
        self.command = message
        self._complete_if_valid()

    def _path_callback(self, message):
        """Retain the latest BRNE path generated by the real shadow node."""
        self.path = message
        self.path_count += 1
        self._complete_if_valid()

    def _complete_if_valid(self):
        """Finish only after input delivery, computation, and both outputs are proven."""
        if self.done or self.inputs_stopped_at is not None or self.command is None or self.path is None:
            return
        if not self.saw_zero_before_inputs:
            return
        if self.shadow_node.compute_count < 3:
            return
        values = (self.command.linear.x, self.command.angular.z)
        if not all(math.isfinite(value) for value in values):
            self.failure = 'raw Twist is not finite'
        elif not 0.0 <= self.command.linear.x <= self.shadow_node.planner.config.max_linear_velocity:
            self.failure = 'raw linear velocity exceeds configured bound'
        elif abs(self.command.angular.z) > self.shadow_node.planner.config.max_angular_velocity:
            self.failure = 'raw angular velocity exceeds configured bound'
        elif self.path.header.frame_id != 'odom' or not self.path.poses:
            self.failure = 'optimal Path has no odom frame or poses'
        elif self.path.header.stamp.sec == 0 and self.path.header.stamp.nanosec == 0:
            self.failure = 'optimal Path has no timestamp'
        elif not all(
            math.isfinite(pose.pose.position.x) and math.isfinite(pose.pose.position.y)
            for pose in self.path.poses
        ):
            self.failure = 'optimal Path contains non-finite positions'
        elif self.command.linear.x <= 0.0:
            self.failure = 'fixture did not observe an active BRNE raw command'
        if self.failure:
            self.done = True
            return
        self.inputs_enabled = False
        self.inputs_stopped_at = time.monotonic()

    def _complete_after_inputs_stop(self):
        """Prove the node fails closed after fresh inputs are intentionally stopped."""
        if not self.post_input_raw_stop_observed:
            return
        if time.monotonic() - self.zero_after_stop_at < 0.3:
            return
        if self.path_count != self.path_count_after_stop:
            self.failure = 'optimal Path was published after inputs became stale'
        elif self.post_input_stop_latency_sec > self.shadow_node.input_timeout_sec + 0.5:
            self.failure = 'raw zero command exceeded bounded stale-input response time'
        self.done = True

    def evidence(self):
        """Return only observable smoke facts, not a success claim by assumption."""
        return {
            'inputs_received': sorted(self.shadow_node._received_at),
            'pre_input_raw_stop_observed': self.saw_zero_before_inputs,
            'post_input_raw_stop_observed': self.post_input_raw_stop_observed,
            'post_input_stop_latency_ms': round(self.post_input_stop_latency_sec * 1000.0, 3),
            'brne_compute_count': self.shadow_node.compute_count,
            'brne_first_compute_ms': round(
                float(self.shadow_node.compute_latencies_ms[0]),
                3,
            ),
            'brne_warm_compute_ms': round(
                float(self.shadow_node.last_compute_ms),
                3,
            ),
            'cmd_linear_x': round(float(self.command.linear.x), 6),
            'cmd_angular_z': round(float(self.command.angular.z), 6),
            'path_frame': self.path.header.frame_id,
            'path_stamp_sec': self.path.header.stamp.sec,
            'path_pose_count': len(self.path.poses),
        }


def main(args=None):
    """Run the node and synthetic fixture in one isolated ROS process."""
    rclpy.init(args=args)
    shadow_node = BrneShadowNode()
    fixture = BrneShadowSmokeFixture(shadow_node)
    executor = rclpy.executors.MultiThreadedExecutor(num_threads=2)
    executor.add_node(shadow_node)
    executor.add_node(fixture)
    try:
        while rclpy.ok() and not fixture.done:
            executor.spin_once(timeout_sec=0.1)
        if fixture.failure:
            raise RuntimeError(fixture.failure)
        print(json.dumps(fixture.evidence(), sort_keys=True))
    finally:
        executor.remove_node(fixture)
        executor.remove_node(shadow_node)
        fixture.destroy_node()
        shadow_node.destroy_node()
        rclpy.shutdown()
